services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    
  boardcamp_api:
    container_name: boardcamp_api
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db 
    env_file:
      - .env 

volumes:
  postgres-data: 